### ISSUE TITLE
HermesMqtt: Reconnecting every 5 seconds

### ISSUE THREAD

**Issue by raufis27** [synesthesiam/rhasspy-hassio-addon#105]
This continues error happens when I enable MQTT microphone:

`[DEBUG:5350314] HermesMqtt: Reconnecting in 5 second(s)
[ERROR:5350313] HermesMqtt: connecting
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/mqtt.py", line 129, in do_connect
    ret = self.client.connect(self.host, self.port)
AttributeError: 'NoneType' object has no attribute 'connect'
[DEBUG:5345309] HermesMqtt: Reconnecting in 5 second(s)
[ERROR:5345309] HermesMqtt: connecting
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/mqtt.py", line 129, in do_connect
    ret = self.client.connect(self.host, self.port)
AttributeError: 'NoneType' object has no attribute 'connect'
[DEBUG:5340304] HermesMqtt: Reconnecting in 5 second(s)
[ERROR:5340303] HermesMqtt: connecting
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/mqtt.py", line 129, in do_connect
    ret = self.client.connect(self.host, self.port)
AttributeError: 'NoneType' object has no attribute 'connect'
[DEBUG:5335301] HermesMqtt: Reconnecting in 5 second(s)
[ERROR:5335301] HermesMqtt: connecting
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/mqtt.py", line 129, in do_connect
    ret = self.client.connect(self.host, self.port)`

**Comment by raufis27** [comment]
Fixed by restarting.
