### ISSUE TITLE
Error fresh install ...

### ISSUE THREAD

**Issue by pploume** [synesthesiam/rhasspy-hassio-addon#186]
Hi,

Unable to start Rhasspy after fresh install on Raspeberry 
Here are the messages : 
5bd9cf270cec: Pull complete
690f382bb10a: Pull complete
48609f288de4: Pull complete
Digest: sha256:144ed18a44dc19357df70ef9deb511ee959b2393dddbd23ff615185a8ff96c00
Status: Downloaded newer image for synesthesiam/rhasspy-server:latest
DEBUG:__main__:Namespace(host='0.0.0.0', log_level='DEBUG', port=12101, profile='fr', set=[], ssl=None, system_profiles='/usr/share/rhasspy/profiles', user_profiles='/profiles')
Traceback (most recent call last):
  File "app.py", line 1319, in <module>
    loop.run_until_complete(start_rhasspy())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "app.py", line 144, in start_rhasspy
    args.profile, system_profiles_dir, user_profiles_dir, actor_system=system
  File "/usr/share/rhasspy/rhasspy/core.py", line 79, in __init__
    self.profile_name, system_profiles_dir, user_profiles_dir
  File "/usr/share/rhasspy/rhasspy/profiles.py", line 32, in __init__
    self.load_profile()
  File "/usr/share/rhasspy/rhasspy/profiles.py", line 85, in load_profile
    recursive_update(self.json, json5.load(profile_file))
  File "/usr/local/lib/python3.6/dist-packages/json5/lib.py", line 42, in load
    object_pairs_hook=object_pairs_hook)
  File "/usr/local/lib/python3.6/dist-packages/json5/lib.py", line 69, in loads
    raise ValueError(err)
ValueError: <string>:29 Unexpected "
" at column 7

Thanks for help
:)

**Comment by synesthesiam** [comment]
This looks like an error in your profile.json file. Can you check that there's not an extra quote somewhere in there?
