### ISSUE TITLE
Docker CLI works but not Docker-compose 

### ISSUE THREAD

**Issue by DavidCarpus** [synesthesiam/rhasspy-hassio-addon#197]
Following instructions for running docker image direct from CLI works.
When I try to run via docker-compose I get errors logged and no intents.

    INFO:quart.serving:172.21.0.1:49728 GET /api/events/log 1.1 101 - 3048002
    ERROR:PocketsphinxDecoder:transcribing wav
    Traceback (most recent call last):
      File "/usr/share/rhasspy/rhasspy/stt.py", line 107, in in_loaded
	        self.load_decoder()
		      File "/usr/share/rhasspy/rhasspy/stt.py", line 179, in load_decoder
	        self.decoder = pocketsphinx.Decoder(decoder_config)
		      File "/usr/local/lib/python3.6/dist-packages/pocketsphinx/pocketsphinx.py", line 273, in __init__
	        this = _pocketsphinx.new_Decoder(*args)
		    RuntimeError: new_Decoder returned -1
    DEBUG:InboxActor: -> stopped
    DEBUG:__main__:
    ERROR:FsticuffsRecognizer:in_loaded
    Traceback (most recent call last):
      File "/usr/share/rhasspy/rhasspy/intent.py", line 166, in in_loaded
	        self.load_graph()
		      File "/usr/share/rhasspy/rhasspy/intent.py", line 211, in load_graph
	        with open(graph_path, "r") as graph_file:
		    FileNotFoundError: [Errno 2] No such file or directory: 'profiles/en/intent.json'
    DEBUG:InboxActor: -> stopped
    DEBUG:__main__:{"text": "", "intent": {"name": "", "confidence": 0}, "entities": [], "raw_text": "", "speech_confidence": 1, "slots": {}, "wakeId": "", "siteId": "default", "time_sec": 1.1776001453399658}

System Info:

    $ uname -a
    Linux dcarpus-Precision-M4800 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
    $ cat /etc/issue
    Ubuntu 18.04.4 LTS \n \l
    $ docker --version
    Docker version 19.03.8, build afacb8b7f0

**Comment by DavidCarpus** [comment]
Not surprisingly, spend a solid day trying to figure this out and within 5 minutes of posting here I realize I forgot to 'train' the instance running via docker-compose. Maybe a few items in the docs with 'getting this error' -> 'try this fix' might be helpful?
