### ISSUE TITLE
NameError: name 'headers' is not defined

### ISSUE THREAD

**Issue by koenvervloesem** [synesthesiam/rhasspy-hassio-addon#21]
I get this error message in the logs when the HomeAssistantIntentHandler handles an intent:

```
ERROR:HomeAssistantIntentHandler:handle_intent
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/intent_handler.py", line 104, in in_started
    intent = self.handle_intent(intent)
  File "/usr/share/rhasspy/rhasspy/intent_handler.py", line 145, in handle_intent
    self.forward_intent(event_type, slots)
  File "/usr/share/rhasspy/rhasspy/intent_handler.py", line 160, in forward_intent
    self._logger.debug("POSTed intent to %s with headers=%s" % (post_url, headers))
NameError: name 'headers' is not defined
```

**Comment by synesthesiam** [comment]
Should be resolved now!
