### ISSUE TITLE
WebSocket errors

### ISSUE THREAD

**Issue by koenvervloesem** [synesthesiam/rhasspy-hassio-addon#22]
I don't use WebSockets, but I see a lot of these error messages in my logs after various events:

```
[ERROR:3744062] __main__: api_events_log
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/geventwebsocket/websocket.py", line 328, in send_frame
    self.raw_write(header + message)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/geventwebsocket/websocket.py", line 344, in send
    self.send_frame(message, opcode)
  File "/usr/local/lib/python3.6/dist-packages/geventwebsocket/websocket.py", line 330, in send_frame
    raise WebSocketError(MSG_SOCKET_DEAD)
geventwebsocket.exceptions.WebSocketError: Socket is dead

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 881, in api_events_log
    ws.send(text)
  File "/usr/local/lib/python3.6/dist-packages/geventwebsocket/websocket.py", line 347, in send
    raise WebSocketError(MSG_SOCKET_DEAD)
geventwebsocket.exceptions.WebSocketError: Socket is dead
```

**Comment by synesthesiam** [comment]
The web interface uses a websocket to pull the log information in real time, and the browser seems to occasionally disconnect for some reason. I should probably just catch the error there are fail silently, since it doesn't really matter (for now). Ultimately, I plan to migrate to [Quart](https://gitlab.com/pgjones/quart) from Flask in hopes that its websocket capabilities will be more robust.
