### ISSUE TITLE
Type error while connecting to mqtt 

### ISSUE THREAD

**Issue by Paul-dH** [synesthesiam/rhasspy-hassio-addon#27]
Hi,

I'm getting a error while Rasspy connects to MQTT, it also generates errors in the MQTT log. It looks like the port value is read as string but compared as int in the connect file.

```
[DEBUG:109299679] HermesMqtt: Reconnecting in 5 second(s)
[ERROR:109299678] HermesMqtt: connecting
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/mqtt.py", line 110, in do_connect
    ret = self.client.connect(self.host, self.port)
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 838, in connect
    self.connect_async(host, port, keepalive, bind_address)
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 894, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
```

My config:
```yaml
    "mqtt": {
        "enabled": true,
        "host": "hassio.local",
        "password": "password",
        "username": "rhasspy",
        "port": 1883,
        "reconnect_sec": 5,
        "site_id": "default",
        "publish_intents": true
    }
```

**Comment by synesthesiam** [comment]
Should be fixed now. Thanks!
