### ISSUE TITLE
Error when training with language model mixing in french

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#48]
I'm unable to use language model mixing in French.

Here is the error I get in the logs:

```
INFO:__main__:Starting training
DEBUG:DialogueManager:asleep -> training_sentences
[2019-12-04 17:39:52,557] 172.17.0.1:38098 GET /api/unknown-words 1.1 200 2 2914
INFO:quart.serving:172.17.0.1:38098 GET /api/unknown-words 1.1 200 2 2914
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python3.6/dist-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python3.6/dist-packages/doit/cmd_base.py", line 420, in execute
    return self._execute(**exec_params)
  File "/usr/local/lib/python3.6/dist-packages/doit/cmd_run.py", line 260, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/usr/local/lib/python3.6/dist-packages/doit/runner.py", line 256, in run_all
    self.run_tasks(task_dispatcher)
  File "/usr/local/lib/python3.6/dist-packages/doit/runner.py", line 219, in run_tasks
    if not self.select_task(node, task_dispatcher.tasks):
  File "/usr/local/lib/python3.6/dist-packages/doit/runner.py", line 107, in select_task
    task = node.task
AttributeError: 'str' object has no attribute 'task'
DEBUG:DialogueManager:training_sentences -> ready
INFO:DialogueManager:Automatically listening for wake word
DEBUG:DialogueManager:ready -> asleep
ERROR:__main__:Training failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.6/dist-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "app.py", line 494, in api_train
    raise Exception(f"Training failed: {result.reason}")
Exception: Training failed:
-- grammars
...
-- intent_fst
-- language_model:intent_counts
-- language_model:intent_model
[2019-12-04 17:39:52,857] 172.17.0.1:38096 POST /api/train 1.1 500 17 304534
INFO:quart.serving:172.17.0.1:38096 POST /api/train 1.1 500 17 304534
```

**Comment by synesthesiam** [comment]
I've pushed a fix for this. Please try again and let me know how it goes!
