### ISSUE TITLE
Mycroft intent handler could not be loaded

### ISSUE THREAD

**Issue by Santobert** [synesthesiam/rhasspy-hassio-addon#56]
There's nothing special about my configuration. I configured mycroft adapt via the web interface.
Do you need some more debug information?

```
[ERROR:267932] AdaptIntentRecognizer: in_loaded
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/intent.py", line 688, in in_loaded
    self.load_engine()
  File "/usr/share/rhasspy/rhasspy/intent.py", line 742, in load_engine
    assert self.engine is not None
AssertionError
```

**Comment by synesthesiam** [comment]
Must have been a bad code merge or something. Fixed now!
