### ISSUE TITLE
Latest docker image does not start

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#68]
Here is the docker run output:
```
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from quart import (
  File "/usr/local/lib/python3.6/dist-packages/quart/__init__.py", line 4, in <module>
    from .app import Quart
  File "/usr/local/lib/python3.6/dist-packages/quart/app.py", line 16, in <module>
    from .asgi import ASGIHTTPConnection, ASGIWebsocketConnection
  File "/usr/local/lib/python3.6/dist-packages/quart/asgi.py", line 5, in <module>
    from .datastructures import CIMultiDict
  File "/usr/local/lib/python3.6/dist-packages/quart/datastructures.py", line 47, in <module>
    class CIMultiDict(_WerkzeugMultidictMixin, AIOCIMultiDict):  # type: ignore
TypeError: type 'multidict._multidict.CIMultiDict' is not an acceptable base type
```

**Comment by synesthesiam** [comment]
Caused by the `multidict` library bumping versions and `quart` apparently not having a hard dependency on it. Re-build in progress.

Should have done a sanity check myself, of course!

**Comment by mathquis** [comment]
The new docker build works :) Thanks @synesthesiam
