### ISSUE TITLE
Default sentences.ini - training error

### ISSUE THREAD

**Issue by frkos** [synesthesiam/rhasspy-hassio-addon#70]
Hello! I've just started to set up Rhasspy and it fails when I try to train it with default profiles/en/sentences.ini

```
Training failed: <Task: ini_graph>: TaskError PythonAction Error Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/doit/action.py", line 437, in execute returned_value = self.py_callable(*self.args, **kwargs) File "/usr/share/rhasspy/rhasspy/train/__init__.py", line 181, in do_intents_to_graph graph = intents_to_graph(intents, replacements) File "/usr/local/lib/python3.6/dist-packages/rhasspynlu/jsgf_graph.py", line 256, in intents_to_graph grammar_name=intent_name, File "/usr/local/lib/python3.6/dist-packages/rhasspynlu/jsgf_graph.py", line 93, in expression_to_graph grammar_name=grammar_name, File "/usr/local/lib/python3.6/dist-packages/rhasspynlu/jsgf_graph.py", line 139, in expression_to_graph grammar_name=grammar_name, File "/usr/local/lib/python3.6/dist-packages/rhasspynlu/jsgf_graph.py", line 72, in expression_to_graph grammar_name=grammar_name, File "/usr/local/lib/python3.6/dist-packages/rhasspynlu/jsgf_graph.py", line 129, in expression_to_graph assert rule_replacements, f"Missing rule {rule_name}" AssertionError: Missing rule <changelightcolor.light_name>
```

As I see the issue is in <ChangeLightColor.light_name> under [ChangeLightState]

```
[ChangeLightState]
light_name = ((living room lamp | garage light) {name}) | <ChangeLightColor.light_name>
light_state = (on | off) {state}
```

When I remove it I see no errors

It's not a critical bug, but it confuses newcomers like me =)

**Comment by synesthesiam** [comment]
Sorry about that! Should be fixed in the latest version.
