### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by Stayer** [synesthesiam/rhasspy-hassio-addon#8]
I'm running inside docker (amd64). When trying to "Save Settings" in Settings tab (after changing language), it writes me "Wrote 1628 byte(s) to /profiles/en/profile.json", but I changed my language. I build image from your github repo (`make docker-amd64`).

The same problem with my RPi3 inside docker

```
 * Serving Flask app "app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
DEBUG:app:Namespace(profile=None, set=[])
DEBUG:RhasspyCore:Loaded profile from /usr/share/rhasspy/profiles/en/profile.json
INFO:root:++++ Actor System gen (3, 9) started, admin @ A@(T|:1900)
DEBUG:root:Thespian source: /usr/local/lib/python3.6/site-packages/thespian/__init__.py
DEBUG:DialogueManager: -> started
DEBUG:DialogueManager:started -> loading_mqtt
DEBUG:DialogueManager:Loading MQTT first
DEBUG:DialogueManager:Loading...will time out after 30 second(s)
DEBUG:HermesMqtt: -> started
DEBUG:DialogueManager:loading_mqtt -> loading
DEBUG:DialogueManager:Loading actors
DEBUG:DialogueManager:Actors created. Waiting for ['recorder', 'player', 'wake', 'command', 'decoder', 'recognizer', 'handler', 'hass_handler', 'sentence_generator', 'speech_trainer', 'intent_trainer', 'word_pronouncer'] to start.
DEBUG:JsgfSentenceGenerator: -> started
DEBUG:APlayAudioPlayer: -> started
DEBUG:HomeAssistantIntentHandler: -> started
DEBUG:PyAudioRecorder: -> started
DEBUG:WebrtcvadCommandListener: -> started
DEBUG:FuzzyWuzzyRecognizer: -> started
DEBUG:DialogueManager:sentence_generator started
DEBUG:HomeAssistantIntentHandler:started -> started
DEBUG:FuzzyWuzzyIntentTrainer: -> started
DEBUG:PocketsphinxSpeechTrainer: -> started
DEBUG:FuzzyWuzzyRecognizer:Loaded examples from /usr/share/rhasspy/profiles/en/intent_examples.json
DEBUG:PhonetisaurusPronounce: -> started
DEBUG:DialogueManager:player started
DEBUG:FuzzyWuzzyRecognizer:started -> loaded
DEBUG:WebrtcvadCommandListener:started -> loaded
DEBUG:DialogueManager:recorder started
DEBUG:DialogueManager:handler started
DEBUG:DialogueManager:intent_trainer started
DEBUG:DialogueManager:command started
DEBUG:DialogueManager:recognizer started
DEBUG:DialogueManager:speech_trainer started
DEBUG:DialogueManager:hass_handler started
DEBUG:DialogueManager:word_pronouncer started
DEBUG:PocketsphinxWakeListener: -> started
DEBUG:PocketsphinxWakeListener:Loading wake decoder with hmm=/usr/share/rhasspy/profiles/en/acoustic_model, dict=/usr/share/rhasspy/profiles/en/dictionary.txt
DEBUG:PocketsphinxWakeListener:started -> loaded
DEBUG:DialogueManager:wake started
DEBUG:PocketsphinxDecoder: -> started
INFO:PocketsphinxDecoder:Loading decoder with hmm=/usr/share/rhasspy/profiles/en/acoustic_model, dict=/usr/share/rhasspy/profiles/en/dictionary.txt, lm=/usr/share/rhasspy/profiles/en/language_model.txt
DEBUG:PocketsphinxDecoder:started -> loaded
DEBUG:DialogueManager:decoder started
DEBUG:PocketsphinxWakeListener:loaded -> listening
DEBUG:PyAudioRecorder:started -> recording
INFO:DialogueManager:Actors loaded
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM dmix
DEBUG:DialogueManager:loading -> ready
INFO:DialogueManager:Automatically listening for wake word
DEBUG:DialogueManager:ready -> asleep
ERROR:PyAudioRecorder:receiveMessage
Traceback (most recent call last):

  File "/usr/share/rhasspy/rhasspy/actor.py", line 50, in receiveMessage
    self._state_method(message, sender)

  File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 104, in in_started
    self.transition('recording')

  File "/usr/share/rhasspy/rhasspy/actor.py", line 76, in transition
    getattr(self, transition_method)(from_state)

  File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 129, in to_recording
    frames_per_buffer=self.frames_per_buffer)

  File "/usr/local/lib/python3.6/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)

OSError: [Errno -9996] Invalid input device (no default output device)

INFO:werkzeug: * Running on http://0.0.0.0:12101/ (Press CTRL+C to quit)
DEBUG:app:Loading phoneme examples from /usr/share/rhasspy/profiles/en/phoneme_examples.txt
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:04] "GET /api/phonemes HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:04] "GET /api/profile?layers=defaults HTTP/1.1" 200 -
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM dmix
ERROR:DialogueManager:receiveMessage
Traceback (most recent call last):

  File "/usr/share/rhasspy/rhasspy/actor.py", line 50, in receiveMessage
    self._state_method(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 174, in in_asleep
    self.handle_any(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 408, in handle_any
    self.handle_forward(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 423, in handle_forward
    mics = recorder_class.get_microphones()

  File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 197, in get_microphones
    default_name = audio.get_default_input_device_info().get('name')

  File "/usr/local/lib/python3.6/site-packages/pyaudio.py", line 949, in get_default_input_device_info
    device_index = pa.get_default_input_device()

OSError: No Default Input Device Available

INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:04] "GET /api/profile?layers=defaults HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:04] "GET /api/profiles HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:04] "GET /api/unknown_words?profile=en HTTP/1.1" 200 -
DEBUG:app:Wrote 5381 byte(s) to /profiles/defaults.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:22] "POST /api/profile?layers=defaults HTTP/1.1" 200 -
DEBUG:app:Wrote 1628 byte(s) to /profiles/en/profile.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:22] "POST /api/profile HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:23] "GET / HTTP/1.1" 200 -
DEBUG:app:Loading phoneme examples from /usr/share/rhasspy/profiles/en/phoneme_examples.txt
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:23] "GET /api/phonemes HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:23] "GET /api/profile?layers=defaults HTTP/1.1" 200 -
ERROR:DialogueManager:receiveMessage
Traceback (most recent call last):

  File "/usr/share/rhasspy/rhasspy/actor.py", line 50, in receiveMessage
    self._state_method(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 174, in in_asleep
    self.handle_any(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 408, in handle_any
    self.handle_forward(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 423, in handle_forward
    mics = recorder_class.get_microphones()

  File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 197, in get_microphones
    default_name = audio.get_default_input_device_info().get('name')

  File "/usr/local/lib/python3.6/site-packages/pyaudio.py", line 949, in get_default_input_device_info
    device_index = pa.get_default_input_device()

OSError: No Default Input Device Available

INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:23] "GET /api/profile?layers=defaults HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:23] "GET /api/profiles HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:23] "GET /api/unknown_words?profile=en HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:24] "GET /img/favicon.png HTTP/1.1" 200 -
DEBUG:app:Wrote 5381 byte(s) to /profiles/defaults.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:39] "POST /api/profile?layers=defaults HTTP/1.1" 200 -
DEBUG:app:Wrote 1681 byte(s) to /profiles/en/profile.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:40] "POST /api/profile HTTP/1.1" 200 -
DEBUG:app:Wrote 5381 byte(s) to /profiles/defaults.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:45] "POST /api/profile?layers=defaults HTTP/1.1" 200 -
DEBUG:app:Wrote 1681 byte(s) to /profiles/en/profile.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:45] "POST /api/profile HTTP/1.1" 200 -
DEBUG:app:Wrote 5381 byte(s) to /profiles/defaults.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:53] "POST /api/profile?layers=defaults HTTP/1.1" 200 -
DEBUG:app:Wrote 1681 byte(s) to /profiles/en/profile.json
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:53] "POST /api/profile HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:56] "GET / HTTP/1.1" 200 -
DEBUG:app:Loading phoneme examples from /usr/share/rhasspy/profiles/en/phoneme_examples.txt
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:57] "GET /api/phonemes HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:57] "GET /api/profile?layers=defaults HTTP/1.1" 200 -
ERROR:DialogueManager:receiveMessage
Traceback (most recent call last):

  File "/usr/share/rhasspy/rhasspy/actor.py", line 50, in receiveMessage
    self._state_method(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 174, in in_asleep
    self.handle_any(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 408, in handle_any
    self.handle_forward(message, sender)

  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 423, in handle_forward
    mics = recorder_class.get_microphones()

  File "/usr/share/rhasspy/rhasspy/audio_recorder.py", line 197, in get_microphones
    default_name = audio.get_default_input_device_info().get('name')

  File "/usr/local/lib/python3.6/site-packages/pyaudio.py", line 949, in get_default_input_device_info
    device_index = pa.get_default_input_device()

OSError: No Default Input Device Available

INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:57] "GET /api/profile?layers=defaults HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:57] "GET /api/profiles HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:57] "GET /api/unknown_words?profile=en HTTP/1.1" 200 -
INFO:werkzeug:95.84.157.26 - - [02/Mar/2019 17:23:57] "GET /img/favicon.png HTTP/1.1" 200 -
```

**Comment by synesthesiam** [comment]
The language is controlled by `rhasspy.default_profile` in the `defaults.json` file inside your profiles directory. Are you mounting a volume into docker to hold your profile data and setting the `RHASSPY_PROFILES` environment variable?

Alternatively, you can just pass `RHASSPY_PROFILE=<language>` as an environment variable to your docker command to force a particular language.
