### ISSUE TITLE
Training failed: local variable 'acoustic_model' referenced before assignment

### ISSUE THREAD

**Issue by drhirn** [synesthesiam/rhasspy-hassio-addon#98]
Updated the docker container a few minutes ago and now I'm getting the above error when trying to train.

```
ERROR:508843] __main__: Training failed: local variable 'acoustic_model' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.6/dist-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "app.py", line 587, in api_train
    raise Exception(f"Training failed: {result.reason}")
Exception: Training failed: local variable 'acoustic_model' referenced before assignment
```

**Comment by mathquis** [comment]
Same for me.

**Comment by drhirn** [comment]
As I just found out, this only happens when using Kaldi for speech recognition.

**Comment by synesthesiam** [comment]
Should be fixed now. Do you see this still?

**Comment by drhirn** [comment]
Nope. Everything's working fine again. Thanks!
